runtime: nodejs14 
handlers:
  - url: /(.*\.(js|css|svg|png)(|\.map))$
    static_files: dist/angular-demo/\1
    upload: dist/angular-demo/(.*)(|\.map)
  - url: /.*
    static_files: dist/angular-demo/index.html
    upload: dist/angular-demo/.*